sudo: required
services:
- docker
language: bash
script:
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- make build
# test image
- make test
- make version
# push image
- >
  if "$TRAVIS_PULL_REQUEST" == "false" ; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    if "$TRAVIS_BRANCH" == "master" ; then
      make push
    else
      docker tag $(DOCKER_IMAGE_TAGNAME) $(DOCKER_IMAGE_NAME):$TRAVIS_BRANCH
      docker push $(DOCKER_IMAGE_NAME):$TRAVIS_BRANCH
    fi
  fi