sudo: required
services:
- docker
language: bash
script:
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t danielrodriguez/docker-spark-raspbian:jdk-1.8.131_hadoop-2.7.3_spark-2.2.1 .
# test image
- docker run --rm danielrodriguez/docker-spark-raspbian:jdk-1.8.131_hadoop-2.7.3_spark-2.2.1 /bin/echo "Success."
#- docker run --rm danielrodriguez/docker-spark-raspbian:jdk-1.8.131_hadoop-2.7.3_spark-2.2.1 spark-shell --version
# push image
- >
  if "$TRAVIS_PULL_REQUEST" == "false" ; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    if "$TRAVIS_BRANCH" == "master" ; then
      docker tag danielrodriguez/docker-spark-raspbian:jdk-1.8.131_hadoop-2.7.3_spark-2.2.1 danielrodriguez/docker-spark-raspbian:latest
      docker push danielrodriguez/docker-spark-raspbian:jdk-1.8.131_hadoop-2.7.3_spark-2.2.1
      docker push danielrodriguez/docker-spark-raspbian
    else
      docker tag danielrodriguez/docker-spark-raspbian:jdk-1.8.131_hadoop-2.7.3_spark-2.2.1 danielrodriguez/docker-spark-raspbian:$TRAVIS_BRANCH
      docker push danielrodriguez/docker-spark-raspbian:$TRAVIS_BRANCH
    fi
  fi