sudo: required

services:
- docker

language: bash

env:
  global:
    - JAVA_VERSION=jdk1.8.131
      HADOOP_VERSION=hadoop-2.7.3
      SPARK_VERSION=spark-2.3.0
      VERSION=${JAVA_VERSION}_${HADOOP_VERSION}_${SPARK_VERSION}
  matrix:
    - ARCH=amd64
      DOCKER_BUILD=danielrodriguez/docker-spark-debian
      DOCKERFILE=Dockerfile.x86_64
    - ARCH=arm
      DOCKER_BUILD=danielrodriguez/docker-spark-raspbian
      DOCKERFILE=Dockerfile.rpi

script:
# prepare qemu
- >
  if [ "$ARCH" == "arm" ]; then
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
  fi
# build image
- docker build -t ${DOCKER_BUILD}:${VERSION} -f ${DOCKERFILE} .
# test image
- docker run --rm ${DOCKER_BUILD}:${VERSION} /bin/echo "Success."
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag ${DOCKER_BUILD}:${VERSION} ${DOCKER_BUILD}:latest
    docker push ${DOCKER_BUILD}:${VERSION}
    docker push ${DOCKER_BUILD}
  elif [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag ${DOCKER_BUILD}:${VERSION} ${DOCKER_BUILD}:$TRAVIS_BRANCH
    docker push ${DOCKER_BUILD}:$TRAVIS_BRANCH
  fi