sudo: required

services:
- docker

language: bash

env:
  global:
    - JAVA_VERSION=jdk1.8.131
      HADOOP_VERSION=hadoop-2.7.3
      SPARK_VERSION=spark-2.2.1
      VERSION=${JAVA_VERSION}_${HADOOP_VERSION}_${SPARK_VERSION}
  matrix:
    - ARCH=x86_64
      DOCKER_BUILD=danielrodriguez/docker-spark-debian
      DOCKERFILE=Dockerfile.x86_64
    - ARCH=armv7l
      DOCKER_BUILD=danielrodriguez/docker-spark-raspbian
      DOCKERFILE=Dockerfile.rpi
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
script:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
# prepare qemu
- >
  if "$ARCH" == "armv7l" ; then
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
  fi
# build image
- docker build -t ${DOCKER_BUILD}:${VERSION} -f ${DOCKERFILE} --platform $ARCH .
# test image
- docker run --rm ${DOCKER_BUILD}:${VERSION} /bin/echo "Success."
#- docker run --rm ${DOCKER_BUILD}:${VERSION} spark-shell --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag ${DOCKER_BUILD}:${VERSION} ${DOCKER_BUILD}:latest
    docker push ${DOCKER_BUILD}:${VERSION}
    docker push ${DOCKER_BUILD}
  elif [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag ${DOCKER_BUILD}:${VERSION} ${DOCKER_BUILD}:$TRAVIS_BRANCH
    docker push ${DOCKER_BUILD}:$TRAVIS_BRANCH
  fi