version: '3.4'

services:

  spark-master:
    image: danielrodriguez/docker-spark-debian
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf/master
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - type: bind
        read_only: true
        source: app
        target: /usr/spark-2.3.0/app
      - type: bind
        source: results
        target: /usr/spark-2.3.0/results
      - type: bind
        source: data
        target: /usr/local/hadoop/data
    deploy:
      placement:
        constraints:
          - node.labels.architecture == x86_64
    networks:
      thesisnet:

  spark-worker:
    image: danielrodriguez/docker-spark-raspbian
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf/worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_MEMORY: 650m
      SPARK_DRIVER_MEMORY: 650m
      SPARK_WORKER_MEMORY: 650m
      SPARK_DAEMON_MEMORY: 650m
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    deploy:
      placement:
        constraints:
          - node.labels.architecture == rpi
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
    networks:
      thesisnet:

  hadoop-master:
    image: sequenceiq/hadoop-docker:2.7.1
    hostname: hadoop-master
    ports:
      - 50070:50070
    deploy:
      placement:
        constraints:
          - node.labels.architecture == x86_64
    networks:
      thesisnet:

networks:
  thesisnet:
    driver: overlay

volumes:
  app:
  data:
  results: